
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
      source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

## Autocompletion initialization
autoload -U compinit
compinit

# Antibody generated script (a.k.a. static loading)
# $ antibody bundle < ~/.zsh/plugins.txt > ~/.zsh/plugins.sh
source ~/.zsh/plugins.sh

source ~/.zsh/config.zsh
source ~/.zsh/key-bindings.zsh
source ~/.zsh/completions.zsh

#source /usr/share/git/completion/git-completion.zsh
source ~/.local/share/fzf/shell/completion.zsh
source ~/.local/share/fzf/shell/key-bindings.zsh

export PATH=$HOME/.local/bin:$PATH

export EDITOR="vim"
export TERM="xterm-256color"

alias ls='ls --color'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh
