---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: kube-common-volume
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
---

